CREATE TABLE "roles" (
  "id_rol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_rol" VARCHAR(50)
);

CREATE TABLE "usuarios" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_usuario" VARCHAR(100),
  "correo" VARCHAR(100) UNIQUE,
  "contrasena" VARCHAR(255),
  "id_rol" INT
);

CREATE TABLE "docentes" (
  "id_docente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100),
  "apellido" VARCHAR(100),
  "correo" VARCHAR(100),
  "telefono" VARCHAR(15),
  "id_usuario" INT
);

CREATE TABLE "director" (
  "id_director" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100),
  "apellido" VARCHAR(100),
  "correo" VARCHAR(100),
  "telefono" VARCHAR(15),
  "fecha_designacion" DATE,
  "id_usuario" INT
);

CREATE TABLE "tutores" (
  "id_tutor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100),
  "apellido" VARCHAR(100),
  "correo" VARCHAR(100),
  "telefono" VARCHAR(15),
  "id_usuario" INT
);

CREATE TABLE "estudiantes" (
  "id_estudiante" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR(100),
  "apellido" VARCHAR(100),
  "fecha_nacimiento" DATE,
  "correo" VARCHAR(100),
  "telefono" VARCHAR(15),
  "id_grupo" INT,
  "fecha_registro" DATE,
  "edad" INT,
  "kinestesico" FLOAT,
  "auditivo" FLOAT,
  "lecto_escritor" FLOAT,
  "visual" FLOAT
);

CREATE TABLE "grupos" (
  "id_grupo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_grupo" VARCHAR(50),
  "id_docente" INT,
  "id_director" INT,
  "fecha_creacion" DATE,
  "grado" VARCHAR(50)
);

CREATE TABLE "actividades_academicas" (
  "id_actividad_academica" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_actividad" VARCHAR(100),
  "descripcion" TEXT,
  "fecha_inicio" DATE,
  "fecha_fin" DATE,
  "id_grupo" INT
);

CREATE TABLE "actividades_kalev" (
  "id_actividad_kalev" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_actividad" VARCHAR(100),
  "descripcion" TEXT,
  "fecha_inicio" DATE,
  "fecha_fin" DATE,
  "id_grupo" INT
);

CREATE TABLE "alumno_actividad_academica" (
  "id_alumno_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_estudiante" INT,
  "id_actividad_academica" INT,
  "estado" VARCHAR(50),
  "calificacion" DECIMAL(5,2)
);

CREATE TABLE "alumno_actividad_kalev" (
  "id_alumno_actividad_kalev" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_estudiante" INT,
  "id_actividad_kalev" INT,
  "estado" VARCHAR(50)
);

CREATE TABLE "rendimiento_estudiante" (
  "id_rendimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_estudiante" INT,
  "nombre_materia" VARCHAR(100),
  "puntaje" INT
);

CREATE TABLE "materias" (
  "id_materia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_materia" VARCHAR(100)
);

CREATE TABLE "temas_materia" (
  "id_tema" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_materia" INT,
  "nombre_tema" VARCHAR(100)
);

CREATE TABLE "caracteristicas_tema" (
  "id_caracteristica" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tema" INT,
  "descripcion" VARCHAR(255)
);

CREATE TABLE "estilos_aprendizaje" (
  "id_tema" INT,
  "estilo_aprendizaje" VARCHAR(50)
);

CREATE TABLE "estrategias_ensenanza" (
  "id_estrategia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" VARCHAR(255),
  "estilo_asociado" VARCHAR(50),
  "id_materia" INT,
  "id_tema" INT
);

CREATE TABLE "historial_recomendaciones" (
  "id_recomendacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_estudiante" INT,
  "id_tema" INT,
  "id_estrategia" INT,
  "efectividad" FLOAT
);

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id_rol");

ALTER TABLE "docentes" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "director" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "tutores" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("id_grupo") REFERENCES "grupos" ("id_grupo");

ALTER TABLE "grupos" ADD FOREIGN KEY ("id_docente") REFERENCES "docentes" ("id_docente");

ALTER TABLE "grupos" ADD FOREIGN KEY ("id_director") REFERENCES "director" ("id_director");

ALTER TABLE "actividades_academicas" ADD FOREIGN KEY ("id_grupo") REFERENCES "grupos" ("id_grupo");

ALTER TABLE "actividades_kalev" ADD FOREIGN KEY ("id_grupo") REFERENCES "grupos" ("id_grupo");

ALTER TABLE "alumno_actividad_academica" ADD FOREIGN KEY ("id_estudiante") REFERENCES "estudiantes" ("id_estudiante");

ALTER TABLE "alumno_actividad_academica" ADD FOREIGN KEY ("id_actividad_academica") REFERENCES "actividades_academicas" ("id_actividad_academica");

ALTER TABLE "alumno_actividad_kalev" ADD FOREIGN KEY ("id_estudiante") REFERENCES "estudiantes" ("id_estudiante");

ALTER TABLE "alumno_actividad_kalev" ADD FOREIGN KEY ("id_actividad_kalev") REFERENCES "actividades_kalev" ("id_actividad_kalev");

ALTER TABLE "rendimiento_estudiante" ADD FOREIGN KEY ("id_estudiante") REFERENCES "estudiantes" ("id_estudiante");

ALTER TABLE "temas_materia" ADD FOREIGN KEY ("id_materia") REFERENCES "materias" ("id_materia");

ALTER TABLE "caracteristicas_tema" ADD FOREIGN KEY ("id_tema") REFERENCES "temas_materia" ("id_tema");

ALTER TABLE "estilos_aprendizaje" ADD FOREIGN KEY ("id_tema") REFERENCES "temas_materia" ("id_tema");

ALTER TABLE "estrategias_ensenanza" ADD FOREIGN KEY ("id_materia") REFERENCES "materias" ("id_materia");

ALTER TABLE "estrategias_ensenanza" ADD FOREIGN KEY ("id_tema") REFERENCES "temas_materia" ("id_tema");

ALTER TABLE "historial_recomendaciones" ADD FOREIGN KEY ("id_estudiante") REFERENCES "estudiantes" ("id_estudiante");

ALTER TABLE "historial_recomendaciones" ADD FOREIGN KEY ("id_tema") REFERENCES "temas_materia" ("id_tema");

ALTER TABLE "historial_recomendaciones" ADD FOREIGN KEY ("id_estrategia") REFERENCES "estrategias_ensenanza" ("id_estrategia");
